version: '3.8'
services:
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "Passw@rd!"
      ACCEPT_EULA: "Y"
    ports:
      - '1433:1433'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local

    